services:
  hello-world:
    command:
      - -c
      - while true; do echo Hello!; sleep 100; done
    entrypoint:
      - /bin/sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    image: busybox
    ports:
      - target: 80
        published: "8080"
    volumes:
      - type: volume
        source: tmp-data
        target: /staging
volumes:
  tmp-data:
